# Generated by Django 5.1.6 on 2025-03-02 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chaivarity',
            old_name='date_addes',
            new_name='date_added',
        ),
    ]
