# Generated by Django 5.1.6 on 2025-03-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0003_chaivarity_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivarity',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
